logging:
  level: INFO
  loggers:
    org.kainos.ea: DEBUG
database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/passport_prototype
  user: USERNAME
  password: PASSWORD
  properties:
    charSet: UTF-8
    currentSchema: public
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
